### ISSUE TITLE
'bundle exec unicorn_rails' stuck in some kind of loop on OS X 10.11

### ISSUE THREAD

**Issue by endquote** [locomotivecms/documentation#191]
After following the OS X install guide for wagon and engine, I got all the way up to the `bundle exec unicorn_rails` command, but end up in some kind of error loop. This sort of thing goes on forever til I kill the process.

```
Obelus:test_cms josh$ bundle exec unicorn_rails
I, [2015-12-27T15:56:46.186405 #57860]  INFO -- : listening on addr=0.0.0.0:8080 fd=9
I, [2015-12-27T15:56:46.186526 #57860]  INFO -- : worker=0 spawning...
I, [2015-12-27T15:56:46.187314 #57860]  INFO -- : master process ready
I, [2015-12-27T15:56:46.188285 #57861]  INFO -- : worker=0 spawned pid=57861
I, [2015-12-27T15:56:46.188660 #57861]  INFO -- : Refreshing Gem list
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/Users/josh/.rvm/gems/ruby-2.2.1/gems/locomotive_liquid-2.4.2/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
/Users/josh/.rvm/gems/ruby-2.2.1/gems/fog-1.12.1/lib/fog/aws/compute.rb:200: warning: duplicated key at line 208 ignored: :internet_gateways
Digest::Digest is deprecated; use Digest
/Users/josh/.rvm/gems/ruby-2.2.1/gems/fog-1.12.1/lib/fog/rackspace/mock_data.rb:41: warning: duplicated key at line 79 ignored: "name"
E, [2015-12-27T15:56:48.080369 #57861] ERROR -- : undefined method `secret_key=' for Devise:Module (NoMethodError)
/Users/josh/Downloads/locomotive/test_cms/config/initializers/devise.rb:4:in `block in <top (required)>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/devise-2.2.7/lib/devise.rb:267:in `setup'
/Users/josh/Downloads/locomotive/test_cms/config/initializers/devise.rb:3:in `<top (required)>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/josh/Downloads/locomotive/test_cms/config/environment.rb:5:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `eval'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `block in builder'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `call'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `block in rails_builder'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `call'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `build_app!'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:617:in `init_worker_process'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:639:in `worker_loop'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/unicorn_rails:23:in `load'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/unicorn_rails:23:in `<main>'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
E, [2015-12-27T15:56:48.088377 #57860] ERROR -- : reaped #<Process::Status: pid 57861 exit 1> worker=0
I, [2015-12-27T15:56:48.088665 #57860]  INFO -- : worker=0 spawning...
I, [2015-12-27T15:56:48.090643 #57862]  INFO -- : worker=0 spawned pid=57862
I, [2015-12-27T15:56:48.091174 #57862]  INFO -- : Refreshing Gem list
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/Users/josh/.rvm/gems/ruby-2.2.1/gems/locomotive_liquid-2.4.2/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
/Users/josh/.rvm/gems/ruby-2.2.1/gems/fog-1.12.1/lib/fog/aws/compute.rb:200: warning: duplicated key at line 208 ignored: :internet_gateways
Digest::Digest is deprecated; use Digest
/Users/josh/.rvm/gems/ruby-2.2.1/gems/fog-1.12.1/lib/fog/rackspace/mock_data.rb:41: warning: duplicated key at line 79 ignored: "name"
E, [2015-12-27T15:56:50.011134 #57862] ERROR -- : undefined method `secret_key=' for Devise:Module (NoMethodError)
/Users/josh/Downloads/locomotive/test_cms/config/initializers/devise.rb:4:in `block in <top (required)>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/devise-2.2.7/lib/devise.rb:267:in `setup'
/Users/josh/Downloads/locomotive/test_cms/config/initializers/devise.rb:3:in `<top (required)>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/josh/Downloads/locomotive/test_cms/config/environment.rb:5:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `eval'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn.rb:46:in `block in builder'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `call'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/bin/unicorn_rails:139:in `block in rails_builder'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `call'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:752:in `build_app!'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:617:in `init_worker_process'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:639:in `worker_loop'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:283:in `join'
/Users/josh/.rvm/gems/ruby-2.2.1/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/unicorn_rails:23:in `load'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/unicorn_rails:23:in `<main>'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/josh/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
E, [2015-12-27T15:56:50.017956 #57860] ERROR -- : reaped #<Process::Status: pid 57862 exit 1> worker=0
I, [2015-12-27T15:56:50.018098 #57860]  INFO -- : worker=0 spawning...
I, [2015-12-27T15:56:50.019711 #57863]  INFO -- : worker=0 spawned pid=57863
I, [2015-12-27T15:56:50.020107 #57863]  INFO -- : Refreshing Gem list
/Users/josh/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.19/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
^CI, [2015-12-27T15:56:50.588528 #57860]  INFO -- : reaped #<Process::Status: pid 57863 exit 0> worker=0
I, [2015-12-27T15:56:50.588662 #57860]  INFO -- : master complete
Obelus:test_cms josh$ 
```

**Comment by endquote** [comment]
The OS X install flow documentation could use a revision in general I think... I had to go through some twists and turns to get things working up to this point, but am unsure if the issues I ran into were specific to me or general to the latest OS version.

**Comment by endquote** [comment]
For what it's worth, I did get it running on another El Capitan machine without too much trouble, so there's clearly some conflict on this system. Maybe the output provides a clue? Unfortunately I'm not very familiar with the Ruby ecosystem...
